services:
  rucio-jupyterlab:
    image: "rucio-jupyterlab"
    build:
      context: .
    profiles:
      - storage
    volumes:
      - ../../certs/rucio_ca.pem:/etc/grid-security/certificates/5fca1cb1.0:z
      - ../../certs/hostcert_rucio.pem:/etc/grid-security/hostcert.pem:z
      - ../../certs/hostcert_rucio.key.pem:/etc/grid-security/hostkey.pem:z
      - ../../certs/rucio_ca.pem:/opt/rucio/etc/rucio_ca.pem:z
      - ../../certs/ruciouser.pem:/opt/rucio/etc/usercert.pem:z
      - ../../certs/ruciouser.key.pem:/opt/rucio/etc/userkey.pem:z
      - ../../../../..:/rucio-jupyterlab:Z
    environment:
      - X509_USER_CERT=/opt/rucio/etc/usercert.pem
      - X509_USER_KEY=/opt/rucio/etc/userkey.pem
      - RUCIO_CA_CERT=/opt/rucio/etc/rucio_ca.pem
    ports:
      - "8888:8888"