name: Build and Publish Extension

on:
  push:
    tags: 'v*'

jobs:
  build:
    name: Build and Publish to PyPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
      - uses: ./.github/actions/test
      - uses: ./.github/actions/build-ext
      - uses: ./.github/actions/post-test
      - name: Build sdist
        run: |
          pip install build
          python -m build --sdist
      - name: Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.pypi_password }}
          skip_existing: true
